// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertProducts implements pgx.CopyFromSource.
type iteratorForInsertProducts struct {
	rows                 []InsertProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Symbol,
		r.rows[0].Locale,
		r.rows[0].Market,
		r.rows[0].Name,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForInsertProducts) Err() error {
	return nil
}

func (q *Queries) InsertProducts(ctx context.Context, arg []InsertProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"product_meta"}, []string{"id", "symbol", "locale", "market", "name", "description"}, &iteratorForInsertProducts{rows: arg})
}
