// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package rdbms

import (
	"context"
)

const getAllMetadata = `-- name: GetAllMetadata :many
SELECT id, symbol, locale, market FROM product_meta
`

type GetAllMetadataRow struct {
	ID     string
	Symbol string
	Locale string
	Market string
}

func (q *Queries) GetAllMetadata(ctx context.Context) ([]GetAllMetadataRow, error) {
	rows, err := q.db.Query(ctx, getAllMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMetadataRow
	for rows.Next() {
		var i GetAllMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Locale,
			&i.Market,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertManyMetadataParams struct {
	ID     string
	Symbol string
	Locale string
	Market string
}
